### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by ylmyg** [halloayu/CameraX#1]
我把拍好的照片存入系统相册的路径，为什么在相册中看不到呢？

**Comment by halloayu** [comment]
要刷新图库吧

**Comment by ylmyg** [comment]
已经做好，目前有个问题，点击拍照屏幕一半会闪一下，背景是黑色的。

**Comment by halloayu** [comment]
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    // Display flash animation to indicate that photo was captured
                    mPreviewFrame.postDelayed(() -> {
                        mPreviewFrame.setForeground(new ColorDrawable(Color.BLACK));
                        mPreviewFrame.postDelayed(() ->
                                mPreviewFrame.setForeground(null), CameraHelper.ANIMATION_SLOW_MILLIS);
                    }, CameraHelper.ANIMATION_FAST_MILLIS);
                }

**Comment by halloayu** [comment]
你可以看着修改，拍照背景变化的代码。主要是体现拍照的效果

**Comment by ylmyg** [comment]
可以了，注释掉就没有显示一半黑色了。
