### ISSUE TITLE
想请教

### ISSUE THREAD

**Issue by ylmyg** [halloayu/CameraX#2]
我把项目移植到我自己的项目中，为什么跳转到拍照界面只显示一半呢，我找不到差别的地方，全部都是你的代码。。

**Comment by halloayu** [comment]
你跑一下demo，我这边小米手机没有问题

**Comment by ylmyg** [comment]
demo 是没有问题的 我移植过来以后就出现半屏 都是想同的代码 我找不到解决的办法。。。

**Comment by halloayu** [comment]
你看你的xml布局文件有没有全屏设置
